appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Wfb2mNOfZi9Ra7jdqsvcc1I0iaBQ2UvQs+ssaRUqQ9BGxfw75dVZexljr0Vt4SfYJaeOwGOge82PMi5L6SXJOKJAjHrT/6HRDMjwKn5KI8CfdeOrC7B/TD+p0WWNZD4e1T4fkBMAkF7KoV3MI+vjy0gYzVVHWQ3ryuk6zuHCPZaX4MsHNObl/3l2rzhPrilEo1AcFawAr6P4txSi6GyNIxnEiR0Xu0Nwl/hW65YUpKkvmSwAeO8C3eYis0mTBSf6YnIwAxHNATwyQ/qYmmEWtzTX5qD92cX893a+EUdwWnZjv8MDxOFVdUMa40ep0yCUt85Yfhd+7Pp8SW0eyPBTTSgS9K5PTjkzKxV/Zjpiqinz1zklAgQfA3Ap8fQzJDUduyzgdZQH2WxWdc7FKyggTZT1WMVonCoy7VnJia60pSySfFIRlAusNUjehVErTDAfcKYsZRPn5y2/rwDPlBAIxe626XbMvBBUF+2gRrb8EV6hIfBHYKubDkWCALpoTsoBJIj0bUoZMRj9vC3cLwdgZvTh64dK2RNcGZRns262mbuhu3b3o3CDPg6pCpioNsmBq3isIB/apuXGMeux/m9J5qOXGSUENfny5eErbO39SEjzE/3pa/5AUM0Mbn2chPAxk3z0pIzFSGEFKWyR1s9hUErSSWR7tMkL7pcbdESy7CY=}
conda_forge_output_validation: true
