travis:
  secure:
    BINSTAR_TOKEN: hpVjtSyEmec435f0jfMmjyrAyQh5ooX60/8DoItJlkgTRVix1PHEN4RaZrtDSUXvxuhKoPdAMc327SqWUvvhDw48PbpY6fYy7iY85qNhiQCv6oamOnrrkB9ZJZ2cfdk7XhTBYCwndpFD7pcATr19ljhxJmuIP7boOYMss5PYDCTXNGSaxUNvubZaQBAxTvv/JRJaTydUsGya1Ioz8U3ZPUO+ftQ6/K9jQ2N6YMNalDLgf2ugp6l6X6fwXkv1Y5E/ww/6UIvagN39OJ2ZcwWZF8HOnaO/Mh5AtHFZQlHnyB6Dbr1O9qbhJHeDoCNErfPEqZTuUUXma00IzWTlxEUZlJeTS+CdkkR2dt7KZj/f/x4rd1zRrMLyqh/tr/OBJNzHlwcG+HEV9+9tj9g3oaaZFupHOxPQJWUDBmKYcQ9N3604fXKJ94tzWp/FstxxO26qVEIIFz2Zm1LgZ5GRnYAxxkxpFEEd201HEXGvjUs/pRUAajZ4HxU1TJuDRA3/iKMxVs3ElwIdB4dfag9LLPes4Gs5m3pI+auEO8RXRAWiK9EXv/uugK0UBcn69qtRzh3+WmC9AazDDQ4ehfcAJjKwbFrzHSsHCIkKQzyOJ2qmP+wypuqZRtMtiS21fxYbBVW4GYHZvLAbj9/1CB7VZ7Yc/5F1Ax+R4b3DTDgMmQB1Pa4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
